version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: movie_bot_bot
    container_name: aiogram_bot
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=8136303197:AAFzGtpJjWduUwHTdPJjy9D0XemKYDY-tyI
    restart: always